# Generated by Django 5.1 on 2024-09-02 04:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Review cant be lower than 0 stars'), django.core.validators.MaxValueValidator(5, 'Review cant be higher than 5 stars')]),
        ),
    ]
